# Site settings
title: Nicholas Ricketts' Professional Site.
description: A site detailing information about Nicholas Ricketts, and why he is a very desirable candidate.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nicholas Ricketts
user_description: |
  Hey, I'm Nicholas! I love a good development challenge and want to contribute to projects with a strong vision. 
  
  My ideal position involves working with driven people creating a product that is beneficial to its users. 
  
  Learning new skills and making myself useful wherever necessary fits my perrsonality type the best! 
  
  If you landed here looking for a valuable, flexible, and passionate software guy, you're in the right place.
user_title: Software Developer
email: nicholasricketts59@gmail.com
twitter_username: lorem_ipsum
github_username:  nri-professional
gplus_username:  lorem_ipsum
github_pfp_link: https://avatars.githubusercontent.com/u/228733848

# Links for the buttons on the header
email_link: mailto:nicholasricketts59@gmail.com
linkedin_link: https://www.linkedin.com/in/nicholasricketts/
github_link: github.com/nri-professional

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
